server:
   port: 9191
spring:
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:mem:testdb
   application:
      name: order-service


eureka:
   client:
      register-with-eureka: true
      fetch-registery: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost
